name: Lint and Format
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Typescript
        run: npm run tsc
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: ESLint
        run: npm run lint
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Prettier
        run: npm run format-check
  vitest:
    name: Typescript - Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Vitest
        run: npm test
  cargo_test:
    name: Rust - Cargo Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Should not update rustup
        shell: bash
        run: rustup set auto-self-update disable
      - run: rustup update nightly && rustup default nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --package hook
      - run: cargo build --verbose
      - run: cargo test --verbose
